# Auto-resolves port conflicts before docker compose up.
# Always runs in auto_increment mode — no manual intervention needed.
# Writes .env.ports with resolved port assignments.
#
# Usage: .\infrastructure\scripts\check_ports.ps1
# Output: .env.ports (consumed by start.ps1)

[Diagnostics.CodeAnalysis.SuppressMessageAttribute('PSUseDeclaredVarsMoreThanAssignments', '', Justification='Script variables used for logging/output.')]
param()

$ScriptDir   = Split-Path -Parent $MyInvocation.MyCommand.Path
$WorkspaceRoot = Resolve-Path (Join-Path $ScriptDir "..\..")
Set-Location $WorkspaceRoot

$ResolvedFile = ".env.ports"

# ── Helpers ───────────────────────────────────────────────────────────────────
function Get-EnvValue([string]$Key, [string]$Default) {
    if (Test-Path ".env") {
        $line = Get-Content ".env" | Where-Object { $_ -match "^$Key=" } | Select-Object -Last 1
        if ($line) { return ($line -replace "^$Key=", "").Trim() }
    }
    return $Default
}

function Test-PortInUse([int]$Port) {
    # First check via Get-NetTCPConnection — catches Docker 127.0.0.1 bindings
    # that TcpListener::Any misses on Windows.
    $active = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue
    if ($active) { return $true }
    # Fallback: try binding to catch any remaining cases
    try {
        $tcp = [System.Net.Sockets.TcpListener]::new([System.Net.IPAddress]::Any, $Port)
        $tcp.Start()
        $tcp.Stop()
        return $false
    } catch {
        return $true
    }
}

function Find-FreePort([int]$Base) {
    # Also read already-resolved ports to avoid double-assigning
    $alreadyAssigned = @()
    if (Test-Path $ResolvedFile) {
        $alreadyAssigned = (Get-Content $ResolvedFile |
            Where-Object { $_ -match "^\w+=\d+$" } |
            ForEach-Object { [int]($_ -split "=")[1] })
    }
    for ($i = 1; $i -le 50; $i++) {
        $candidate = $Base + $i
        if (-not (Test-PortInUse $candidate) -and $candidate -notin $alreadyAssigned) {
            return $candidate
        }
    }
    throw "No free port found near $Base (searched +1..+50)"
}

# ── Port defaults ─────────────────────────────────────────────────────────────
$PortKeys = [ordered]@{
    WA_CLIENT_1_HOST_PORT              = 3011
    WA_CLIENT_2_HOST_PORT              = 3012
    COLLECTOR_METRICS_PORT             = 9090
    MEDIA_ARCHIVAL_METRICS_PORT        = 9091
    FACE_RECOGNITION_METRICS_PORT      = 9092
    USER_INTELLIGENCE_METRICS_PORT     = 9093
    LINK_DISCOVERY_METRICS_PORT        = 9094
    BULK_SENDER_METRICS_PORT           = 9095
    DASHBOARD_PORT                     = 8700
}

# ── Main resolution loop ──────────────────────────────────────────────────────
$lines = @(
    "# Auto-generated by check_ports.ps1 - do not edit manually",
    "# Generated: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ss' -ErrorAction SilentlyContinue)Z",
    ""
)
Set-Content -Path $ResolvedFile -Value $lines

$Conflicts = 0

foreach ($var in $PortKeys.Keys) {
    $default = $PortKeys[$var]
    $port    = [int](Get-EnvValue -Key $var -Default $default)

    # Read already-assigned ports each iteration so previous assignments are visible
    $alreadyAssigned = @()
    if (Test-Path $ResolvedFile) {
        $alreadyAssigned = (Get-Content $ResolvedFile |
            Where-Object { $_ -match "^\w+=\d+$" } |
            ForEach-Object { [int]($_ -split "=")[1] })
    }

    if ((Test-PortInUse $port) -or ($port -in $alreadyAssigned)) {
        $free = Find-FreePort $port
        Write-Host "  !! $var`: $port in use -> reassigned to $free" -ForegroundColor Yellow
        Add-Content -Path $ResolvedFile -Value "${var}=${free}"
        $Conflicts++
    } else {
        Add-Content -Path $ResolvedFile -Value "${var}=${port}"
    }
}

Write-Host ""
if ($Conflicts -gt 0) {
    Write-Host "  OK  $Conflicts port(s) auto-reassigned. See $ResolvedFile" -ForegroundColor Green
} else {
    Write-Host "  OK  All ports free. No conflicts." -ForegroundColor Green
}
