#!/usr/bin/env bash
# Auto-resolves port conflicts before docker compose up.
# Always runs in auto_increment mode — no manual intervention needed.
# Writes .env.ports with resolved port assignments.
#
# Usage: ./infrastructure/scripts/check_ports.sh
# Output: .env.ports (sourced by start.sh)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WORKSPACE_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$WORKSPACE_ROOT"

RESOLVED_FILE=".env.ports"

# ── Default ports ────────────────────────────────────────────────────────────
# Load from .env if present, fall back to hardcoded defaults
load_env_value() {
    local key="$1" default="$2"
    if [[ -f .env ]]; then
        local val
        val=$(grep -E "^${key}=" .env 2>/dev/null | tail -1 | cut -d'=' -f2- | tr -d '\r' || true)
        [[ -n "$val" ]] && echo "$val" && return
    fi
    echo "$default"
}

declare -A PORT_DEFAULTS=(
    [WA_CLIENT_1_HOST_PORT]=3011
    [WA_CLIENT_2_HOST_PORT]=3012
    [DASHBOARD_INDEX_PORT]=8500
    [COLLECTOR_DASHBOARD_PORT]=8501
    [MEDIA_ARCHIVAL_DASHBOARD_PORT]=8502
    [FACE_RECOGNITION_DASHBOARD_PORT]=8503
    [USER_INTELLIGENCE_DASHBOARD_PORT]=8504
    [LINK_DISCOVERY_DASHBOARD_PORT]=8505
    [BULK_SENDER_DASHBOARD_PORT]=8506
    [COLLECTOR_METRICS_PORT]=9090
    [MEDIA_ARCHIVAL_METRICS_PORT]=9091
    [FACE_RECOGNITION_METRICS_PORT]=9092
    [USER_INTELLIGENCE_METRICS_PORT]=9093
    [LINK_DISCOVERY_METRICS_PORT]=9094
    [BULK_SENDER_METRICS_PORT]=9095
)

# ── Port probe ────────────────────────────────────────────────────────────────
port_in_use() {
    local port=$1
    # Try netstat first (widely available on Windows/Linux/macOS)
    if command -v netstat &>/dev/null; then
        netstat -an 2>/dev/null | grep -qE "(^|[[:space:]])0\.0\.0\.0:${port}[[:space:]]|:::${port}[[:space:]]|LISTENING" && \
        netstat -an 2>/dev/null | grep -qE ":${port}[[:space:]]" && return 0 || true
    fi
    # Fallback: Python socket bind test (cross-platform)
    python3 - "$port" <<'PYEOF' 2>/dev/null
import socket, sys
port = int(sys.argv[1])
s = socket.socket()
s.settimeout(0.5)
try:
    s.bind(('', port))
    s.close()
    sys.exit(1)   # free
except OSError:
    sys.exit(0)   # in use
PYEOF
}

# More reliable cross-platform check using Python
port_in_use() {
    local port=$1
    python3 - "$port" <<'PYEOF' 2>/dev/null
import socket, sys
port = int(sys.argv[1])
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.settimeout(0.3)
try:
    s.bind(('', port))
    s.close()
    sys.exit(1)   # free → exit 1 so bash treats as "not in use"
except OSError:
    sys.exit(0)   # in use → exit 0 so bash treats as "in use"
PYEOF
}

find_free_port() {
    local base=$1
    # Also track ports we've already assigned in this run
    local candidate
    for i in $(seq 1 50); do
        candidate=$((base + i))
        if ! port_in_use "$candidate" && ! grep -q "=${candidate}$" "$RESOLVED_FILE" 2>/dev/null; then
            echo "$candidate"
            return 0
        fi
    done
    echo "ERROR: No free port found near $base (searched +1..+50)" >&2
    return 1
}

# ── Main resolution loop ──────────────────────────────────────────────────────
echo "# Auto-generated by check_ports.sh — do not edit manually" > "$RESOLVED_FILE"
echo "# Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')" >> "$RESOLVED_FILE"
echo "" >> "$RESOLVED_FILE"

CONFLICTS=0

# Preserve insertion order by using an array of keys
PORT_KEYS=(
    WA_CLIENT_1_HOST_PORT
    WA_CLIENT_2_HOST_PORT
    DASHBOARD_INDEX_PORT
    COLLECTOR_DASHBOARD_PORT
    MEDIA_ARCHIVAL_DASHBOARD_PORT
    FACE_RECOGNITION_DASHBOARD_PORT
    USER_INTELLIGENCE_DASHBOARD_PORT
    LINK_DISCOVERY_DASHBOARD_PORT
    BULK_SENDER_DASHBOARD_PORT
    COLLECTOR_METRICS_PORT
    MEDIA_ARCHIVAL_METRICS_PORT
    FACE_RECOGNITION_METRICS_PORT
    USER_INTELLIGENCE_METRICS_PORT
    LINK_DISCOVERY_METRICS_PORT
    BULK_SENDER_METRICS_PORT
)

for var in "${PORT_KEYS[@]}"; do
    default="${PORT_DEFAULTS[$var]}"
    port=$(load_env_value "$var" "$default")

    if port_in_use "$port"; then
        free=$(find_free_port "$port")
        echo "  ⚠  $var: $port in use → reassigned to $free"
        echo "${var}=${free}" >> "$RESOLVED_FILE"
        CONFLICTS=$((CONFLICTS + 1))
    else
        echo "${var}=${port}" >> "$RESOLVED_FILE"
    fi
done

echo ""
if [[ $CONFLICTS -gt 0 ]]; then
    echo "  ✔  $CONFLICTS port(s) auto-reassigned. See $RESOLVED_FILE"
else
    echo "  ✔  All ports free. No conflicts."
fi
