services:
  wa-client-ts-1:
    volumes:
      - ./services/wa-client-ts/src:/app/src
      - ./services/wa-client-ts/package.json:/app/package.json
      - ./services/wa-client-ts/tsconfig.json:/app/tsconfig.json
    environment:
      - LOG_LEVEL=debug
    ports:
      - "9229:9229" # Node.js inspector port

  wa-client-ts-2:
    volumes:
      - ./services/wa-client-ts/src:/app/src
      - ./services/wa-client-ts/package.json:/app/package.json
      - ./services/wa-client-ts/tsconfig.json:/app/tsconfig.json
    environment:
      - LOG_LEVEL=debug

  collector:
    environment:
      - PYTHON_LOG_LEVEL=DEBUG
    ports:
      - "5678:5678" # debugpy

  media_archival:
    environment:
      - PYTHON_LOG_LEVEL=DEBUG

  face_recognition:
    environment:
      - PYTHON_LOG_LEVEL=DEBUG

  user_intelligence:
    environment:
      - PYTHON_LOG_LEVEL=DEBUG

  link_discovery:
    environment:
      - PYTHON_LOG_LEVEL=DEBUG

  bulk_sender:
    environment:
      - PYTHON_LOG_LEVEL=DEBUG
