-- Fix collection_targets priorities and add missing targets
-- Run: docker exec unifiedcollector_postgres psql -U collector -d unifiedcollector -f /migrations/fix_targets_priorities.sql
-- Generated by Hermes Agent, 2026-05-29

BEGIN;

-- =====================================================================
-- INSTAGRAM: bump OWN/private accounts to priority 10, public to 5
-- Private (Bryan's own): bryanseah234, cchmsmediaclub, oopspwned,
--   prawnproductions234, shotsbyseah234
-- Public large accounts go last (priority 1)
-- =====================================================================
UPDATE collection_targets SET priority = 10
WHERE source = 'instagram'
  AND target_id IN ('bryanseah234','cchmsmediaclub','oopspwned','prawnproductions234','shotsbyseah234');

UPDATE collection_targets SET priority = 3
WHERE source = 'instagram'
  AND target_id = 'streets.of.singapore';

UPDATE collection_targets SET priority = 1
WHERE source = 'instagram'
  AND target_id IN ('humansofny','natgeo','makrosnapz');

-- =====================================================================
-- TIKTOK: own account + close friends first
-- shotsbyseah234 = Bryan's own TikTok → priority 10
-- libraryofsix = known close follow → priority 8
-- =====================================================================
UPDATE collection_targets SET priority = 10
WHERE source = 'tiktok' AND target_id = 'shotsbyseah234';

UPDATE collection_targets SET priority = 8
WHERE source = 'tiktok' AND target_id = 'libraryofsix';

-- =====================================================================
-- YOUTUBE: remove wrong channels (MKBHD/Kurzgesagt/PewDiePie test data)
-- Keep UC-lHJZR3Gqxm24_Vd_AJ5Yw (likely Bryan's channel)
-- =====================================================================
DELETE FROM collection_targets
WHERE source = 'youtube'
  AND target_id IN (
    'UCBJycsmduvYEL83R_U4JriQ',  -- MKBHD 21M subs
    'UCsBjURrPoezykLs9EqgamOA',  -- Kurzgesagt 25M subs
    'UCsXVk37bltHxD1rDPwtNM8Q'   -- PewDiePie 110M subs
  );

-- Also remove from youtube_channels and youtube_videos for those channels
-- (keep DB clean)
DELETE FROM youtube_videos WHERE channel_id IN (
  SELECT id FROM youtube_channels
  WHERE id::text IN (
    SELECT uc.id::text FROM youtube_channels uc
    JOIN collection_targets ct ON ct.target_id = uc.platform_channel_id
    WHERE ct.source = 'youtube'
  )
);

-- =====================================================================
-- LEMON8: add more seed targets (Bryan's friends on Lemon8)
-- bryanseah is already there; add known handles
-- =====================================================================
INSERT INTO collection_targets (source, target_id, status, priority, created_at)
VALUES
  ('lemon8', 'shotsbyseah', 'pending', 10, NOW()),
  ('lemon8', 'prawnproductions', 'pending', 8, NOW()),
  ('lemon8', 'makrosnapz', 'pending', 5, NOW()),
  ('lemon8', 'streets.of.singapore', 'pending', 5, NOW())
ON CONFLICT (source, target_id) DO NOTHING;

UPDATE collection_targets SET priority = 10
WHERE source = 'lemon8' AND target_id = 'bryanseah';

-- =====================================================================
-- GITHUB: increase batch size via env (not DB), but bump priority for
-- close connections
-- =====================================================================
UPDATE collection_targets SET priority = 10
WHERE source = 'github' AND target_id = 'bryanseah234';

UPDATE collection_targets SET priority = 3
WHERE source = 'github'
  AND target_id IN ('elliotwutingfeng');

-- =====================================================================
-- TELEGRAM: bump private/personal channels to higher priority
-- shotsbyseah234 = Bryan's own channel
-- =====================================================================
UPDATE collection_targets SET priority = 10
WHERE source = 'telegram' AND target_id = 'shotsbyseah234';

-- =====================================================================
-- STRAVA: keep as-is (needs API creds or cookies for full data)
-- =====================================================================

COMMIT;

SELECT source, target_id, priority, status
FROM collection_targets
WHERE source IN ('instagram','tiktok','youtube','lemon8','github','telegram')
ORDER BY source, priority DESC, target_id;
