#!/usr/bin/env python3
"""Reads all legacy toolkit .env files and generates a unified .env for UnifiedCollector.

Usage:
    python scripts/migrate_env.py              # writes .env (prompts before overwriting)
    python scripts/migrate_env.py --dry-run    # prints to stdout only
    python scripts/migrate_env.py --force      # overwrites without prompting
"""

import argparse
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / ".env"

TOOLKIT_ENVS = {
    "github":    ROOT / "githubtoolkit" / ".env",
    "instagram": ROOT / "instagramtoolkit" / ".env",
    "telegram_collector": ROOT / "telegramcollector" / ".env",
    "telegram_toolkit":   ROOT / "telegramtoolkit" / ".env",
    "youtube":   ROOT / "youtubetoolkit" / ".env",
    "strava":    ROOT / "stravatoolkit" / "data" / ".env",
    "strava_tpl": ROOT / "stravatoolkit" / ".env.template",
    "tiktok":    ROOT / "tiktoktoolkit" / ".env",
    "lemon8":    ROOT / "lemon8toolkit" / ".env",
    "search":    ROOT / "searchtoolkit" / ".env",
    "website":   ROOT / "websitetoolkit" / ".env",
    "whatsapp":  ROOT / "whatsappcollector" / ".env",
}


def read_env(path: Path) -> dict[str, str]:
    vals = {}
    if not path.exists():
        return vals
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        key, _, val = line.partition("=")
        vals[key.strip()] = val.strip()
    return vals


def build_unified() -> str:
    envs = {k: read_env(v) for k, v in TOOLKIT_ENVS.items()}
    missing = [k for k, v in TOOLKIT_ENVS.items() if not v.exists()]
    if missing:
        print(f"Warning: missing env files for: {', '.join(missing)}", file=sys.stderr)

    gh  = envs.get("github", {})
    ig  = envs.get("instagram", {})
    tgc = envs.get("telegram_collector", {})
    tgt = envs.get("telegram_toolkit", {})
    yt  = envs.get("youtube", {})
    st  = envs.get("strava", {})
    stt = envs.get("strava_tpl", {})
    tt  = envs.get("tiktok", {})
    l8  = envs.get("lemon8", {})
    sr  = envs.get("search", {})
    ws  = envs.get("website", {})
    wa  = envs.get("whatsapp", {})

    lines = []

    def section(title):
        lines.append("")
        lines.append(f"# -- {title} {'-' * (55 - len(title))}")

    def var(key, val, comment=None):
        c = f"  # {comment}" if comment else ""
        lines.append(f"{key}={val}{c}")

    def commented(key, val, comment=None):
        c = f"  # {comment}" if comment else ""
        lines.append(f"# {key}={val}{c}")

    lines.append("# UnifiedCollector — Unified Environment Configuration")
    lines.append("# Auto-generated by scripts/migrate_env.py from legacy toolkit .env files.")
    lines.append("# Review and adjust values before use.")

    section("Database")
    var("DATABASE_URL", "postgres://collector:collector@localhost:5432/unifiedcollector")
    var("POSTGRES_USER", "collector")
    var("POSTGRES_PASSWORD", "collector")

    section("Storage")
    var("COLLECTOR_DRIVE_PATH", "Z:/media")

    # ── GitHub ─────────────────────────────────────────────
    section("GitHub")
    lines.append("# Migrated from: githubtoolkit/.env → GITHUB_PAT (renamed to GITHUB_TOKEN)")
    var("GITHUB_TOKEN", gh.get("GITHUB_PAT", ""), "comma-separated PATs")
    var("GITHUB_AVATAR_SIZE", gh.get("AVATAR_SIZE", "460"))
    var("GITHUB_API_DELAY", gh.get("API_REQUEST_DELAY", "0.1"))
    var("GITHUB_MAX_CONCURRENT", gh.get("MAX_CONCURRENT_API_REQUESTS", "5"))
    var("GITHUB_SPIDER_DEPTH", gh.get("DEFAULT_SPIDER_DEPTH", "4"))
    var("GITHUB_DOWNLOAD_DELAY", gh.get("AVATAR_DOWNLOAD_DELAY", "0.5"))
    var("GITHUB_PROFILE_PHOTO_BLOB_MAX_SIZE_MB", gh.get("PROFILE_PHOTO_BLOB_MAX_SIZE_MB", "5000"))

    # ── Instagram ──────────────────────────────────────────
    section("Instagram")
    lines.append("# Migrated from: instagramtoolkit/.env (username/password auth via Instaloader)")
    for i in range(1, 6):
        name = ig.get(f"INSTA_ACCOUNT_{i}_NAME", "")
        user = ig.get(f"INSTA_ACCOUNT_{i}_USER", "")
        pw   = ig.get(f"INSTA_ACCOUNT_{i}_PASS", "")
        if name or user:
            var(f"INSTA_ACCOUNT_{i}_NAME", name)
            var(f"INSTA_ACCOUNT_{i}_USER", user)
            var(f"INSTA_ACCOUNT_{i}_PASS", pw)
    var("FILTER_MAX_FOLLOWERS", ig.get("FILTER_MAX_FOLLOWERS", "960"))
    var("SLIDING_WINDOW_ENABLED", ig.get("SLIDING_WINDOW_ENABLED", "false"))
    var("WINDOW_1H_LIMIT", ig.get("WINDOW_1H_LIMIT", "180"))
    var("WINDOW_3H_LIMIT", ig.get("WINDOW_3H_LIMIT", "400"))
    var("WINDOW_5H_LIMIT", ig.get("WINDOW_5H_LIMIT", "600"))
    var("WINDOW_1D_LIMIT", ig.get("WINDOW_1D_LIMIT", "2000"))

    # ── Telegram ───────────────────────────────────────────
    section("Telegram")
    lines.append("# Migrated from: telegramcollector/.env (TG_API_ID→TELEGRAM_API_ID)")
    lines.append("# and telegramtoolkit/.env (multi-account sessions)")
    var("TELEGRAM_API_ID", tgc.get("TG_API_ID", ""))
    var("TELEGRAM_API_HASH", tgc.get("TG_API_HASH", ""))
    var("TELEGRAM_BOT_TOKEN", tgc.get("BOT_TOKEN", ""))
    var("TELEGRAM_BOT_TOKENS", tgc.get("BOT_TOKENS", ""))
    var("TELEGRAM_HUB_GROUP", tgc.get("HUB_GROUP_ID", ""))
    var("TELEGRAM_STORY_SCAN_INTERVAL", tgc.get("STORY_SCAN_INTERVAL", "300"))
    var("TELEGRAM_STORY_SCAN_ENABLED", tgc.get("STORY_SCAN_ENABLED", "true"))
    var("TELEGRAM_BACKFILL_ENABLED", tgc.get("COLLECTOR_BACKFILL_ENABLED", "true"))
    var("TELEGRAM_BACKFILL_MSG_PER_SEC", tgc.get("COLLECTOR_BACKFILL_MSG_PER_SEC", "20.0"))
    var("TELEGRAM_BACKFILL_BATCH_SIZE", tgc.get("COLLECTOR_BACKFILL_BATCH_SIZE", "100"))
    var("TELEGRAM_MAX_MEDIA_SIZE_MB", tgc.get("COLLECTOR_MAX_MEDIA_SIZE_MB", "50"))
    lines.append("# Multi-session accounts (from telegramtoolkit/.env)")
    for i in range(1, 5):
        name  = tgt.get(f"ACCOUNT_{i}_NAME", "")
        api_id = tgt.get(f"ACCOUNT_{i}_API_ID", "")
        api_hash = tgt.get(f"ACCOUNT_{i}_API_HASH", "")
        phone = tgt.get(f"ACCOUNT_{i}_PHONE", "")
        session = tgt.get(f"ACCOUNT_{i}_SESSION", "")
        prefix = tgt.get(f"ACCOUNT_{i}_PREFIX", "")
        if name:
            var(f"TELEGRAM_ACCOUNT_{i}_NAME", name)
            var(f"TELEGRAM_ACCOUNT_{i}_API_ID", api_id)
            var(f"TELEGRAM_ACCOUNT_{i}_API_HASH", api_hash)
            var(f"TELEGRAM_ACCOUNT_{i}_PHONE", phone)
            var(f"TELEGRAM_ACCOUNT_{i}_SESSION", session)
            var(f"TELEGRAM_ACCOUNT_{i}_PREFIX", prefix)

    # ── YouTube ────────────────────────────────────────────
    section("YouTube")
    lines.append("# Migrated from: youtubetoolkit/.env (kept var names)")
    var("YOUTUBE_API_KEY", yt.get("YOUTUBE_API_KEY", ""))
    var("YOUTUBE_CLIENT_ID", yt.get("YOUTUBE_CLIENT_ID", ""))
    var("YOUTUBE_CLIENT_SECRET", yt.get("YOUTUBE_CLIENT_SECRET", ""))
    var("YOUTUBE_COOKIE_BROWSER", yt.get("YOUTUBE_COOKIE_BROWSER", "auto"))
    var("YOUTUBE_MAX_VIDEO_DURATION_MINUTES", yt.get("YOUTUBE_MAX_VIDEO_DURATION_MINUTES", "18"))
    var("YOUTUBE_YTDLP_FORMAT", yt.get("YOUTUBE_YTDLP_FORMAT", "best"))
    var("YOUTUBE_DOWNLOAD_DELAY", yt.get("YOUTUBE_DOWNLOAD_DELAY_SECONDS", "5.0"))
    var("YOUTUBE_API_DELAY", yt.get("YOUTUBE_API_DELAY_SECONDS", "3.0"))
    var("YOUTUBE_MAX_CONCURRENT_DOWNLOADS", yt.get("YOUTUBE_MAX_CONCURRENT_DOWNLOADS", "3"))
    var("YOUTUBE_PROFILE_PHOTO_BLOB_MAX_SIZE_MB", yt.get("YOUTUBE_PROFILE_PHOTO_BLOB_MAX_SIZE_MB", "5000"))

    # ── Strava ─────────────────────────────────────────────
    section("Strava")
    lines.append("# Migrated from: stravatoolkit/data/.env + .env.template")
    var("STRAVA_SESSION_COOKIE", st.get("STRAVA_SESSION_COOKIE", ""), "web scraping mode")
    commented("STRAVA_CLIENT_ID", "", "OAuth mode (create at developers.strava.com)")
    commented("STRAVA_CLIENT_SECRET", "")
    commented("STRAVA_REFRESH_TOKEN", "")
    var("STRAVA_API_DELAY_MIN", stt.get("API_DELAY_MIN_SECONDS", "5.0"))
    var("STRAVA_API_DELAY_MAX", stt.get("API_DELAY_MAX_SECONDS", "10.0"))
    var("STRAVA_FEED_DELAY_MIN", stt.get("FEED_DELAY_MIN_SECONDS", "5.0"))
    var("STRAVA_FEED_DELAY_MAX", stt.get("FEED_DELAY_MAX_SECONDS", "12.0"))
    var("STRAVA_BACKFILL_DELAY_MIN", stt.get("BACKFILL_DELAY_MIN_SECONDS", "5.0"))
    var("STRAVA_BACKFILL_DELAY_MAX", stt.get("BACKFILL_DELAY_MAX_SECONDS", "15.0"))
    var("STRAVA_BACKFILL_STEPS", stt.get("BACKFILL_STEPS", "25"))
    var("STRAVA_BACKFILL_PARALLELISM", stt.get("BACKFILL_PARALLELISM", "3"))
    var("STRAVA_PROFILE_PHOTO_BLOB_MAX_SIZE_MB", stt.get("PROFILE_PHOTO_BLOB_MAX_SIZE_MB", "5000"))

    # ── TikTok ─────────────────────────────────────────────
    section("TikTok")
    lines.append("# Migrated from: tiktoktoolkit/.env")
    var("TIKTOK_COOKIES_FILE", tt.get("TIKTOK_COOKIES_FILE", "configs/tiktok_cookies.txt"))
    var("TIKTOK_SESSION_ID", "")
    var("TIKTOK_MIN_SLEEP", tt.get("TIKTOK_MIN_SLEEP", "0.5"))
    var("TIKTOK_MAX_SLEEP", tt.get("TIKTOK_MAX_SLEEP", "2.0"))
    var("TIKTOK_RETRIES", tt.get("TIKTOK_RETRIES", "2"))
    var("TIKTOK_TIMEOUT_SECONDS", tt.get("TIKTOK_TIMEOUT_SECONDS", "300"))
    var("TIKTOK_BROWSER_FALLBACK_ENABLED", tt.get("TIKTOK_BROWSER_FALLBACK_ENABLED", "true"))
    var("TIKTOK_YTDLP_FALLBACK_ENABLED", tt.get("TIKTOK_YTDLP_FALLBACK_ENABLED", "true"))
    var("TIKTOK_USER_AGENT", tt.get("TIKTOK_USER_AGENT", ""))

    # ── Lemon8 ─────────────────────────────────────────────
    section("Lemon8")
    lines.append("# Migrated from: lemon8toolkit/.env")
    var("LEMON8_COOKIES_FILE", l8.get("LEMON8_COOKIES_FILE", "cookies.txt"))
    var("LEMON8_MIN_WIDTH", l8.get("MIN_IMAGE_WIDTH", "320"))
    var("LEMON8_MIN_HEIGHT", l8.get("MIN_IMAGE_HEIGHT", "320"))
    var("LEMON8_MIN_FILE_SIZE", l8.get("MIN_IMAGE_FILE_SIZE_BYTES", "8192"))
    var("LEMON8_HIGH_QUALITY_WIDTH", l8.get("HIGH_QUALITY_IMAGE_WIDTH", "2160"))
    var("LEMON8_PROFILE_PHOTO_ENABLED", l8.get("PROFILE_PHOTO_DOWNLOAD_ENABLED", "true"))
    var("LEMON8_IMAGE_ENHANCEMENT", l8.get("IMAGE_ENHANCEMENT_ENABLED", "true"))
    var("LEMON8_MIN_DELAY", l8.get("MIN_DELAY", "1"))
    var("LEMON8_MAX_DELAY", l8.get("MAX_DELAY", "3"))

    # ── Search ─────────────────────────────────────────────
    section("Search")
    lines.append("# Migrated from: searchtoolkit/.env")
    var("SEARCH_API_KEY", sr.get("SERPER_API_KEY", ""))
    var("SERPER_API_KEY", sr.get("SERPER_API_KEY", ""), "alias for backward compat")
    var("SEARCH_MIN_DIMENSION", sr.get("MIN_IMAGE_DIMENSION", "200"))
    var("SEARCH_MIN_FILE_SIZE", sr.get("MIN_FILE_SIZE_BYTES", "10240"))
    var("SEARCH_CACHE_TTL_HOURS", sr.get("SEARCH_CACHE_TTL_HOURS", "24"))

    # ── Website ────────────────────────────────────────────
    section("Website")
    lines.append("# Migrated from: websitetoolkit/.env")
    var("WEBSITE_MAX_DEPTH", "3")
    var("WEBSITE_MAX_PAGES", "500")
    var("WEBSITE_USE_TOR", ws.get("USE_TOR", "false"))
    var("WEBSITE_TIMEOUT", ws.get("WEBSITE_TIMEOUT", "30"))
    var("WEBSITE_MAX_CONCURRENT_TASKS", ws.get("WEBSITE_MAX_CONCURRENT_TASKS", "5"))

    # ── WhatsApp ───────────────────────────────────────────
    section("WhatsApp")
    lines.append("# Migrated from: whatsappcollector/.env")
    lines.append("# Full real-time rebuild will need additional services (RabbitMQ, Redis, wa-client-ts)")
    var("WHATSAPP_EXPORT_DIR", "", "offline export reader mode")
    lines.append("# Real-time mode credentials (from whatsappcollector/.env)")
    var("WHATSAPP_SESSION_NAMES", wa.get("SESSION_NAMES", "session_1,session_2"))
    var("WHATSAPP_MEDIA_BRIDGE_SECRET", wa.get("MEDIA_BRIDGE_SECRET", ""))
    var("WHATSAPP_FINDINGS_HUB_GROUP_JID", wa.get("FINDINGS_HUB_GROUP_JID", ""))
    var("WHATSAPP_RABBITMQ_URL", wa.get("RABBITMQ_URL", ""))
    var("WHATSAPP_REDIS_URL", wa.get("REDIS_URL", ""))

    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description="Generate unified .env from legacy toolkit .env files")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout, don't write file")
    parser.add_argument("--force", action="store_true", help="Overwrite existing .env without prompting")
    args = parser.parse_args()

    content = build_unified()

    if args.dry_run:
        print(content)
        return

    if OUTPUT.exists() and not args.force:
        resp = input(f"{OUTPUT} already exists. Overwrite? [y/N] ")
        if resp.lower() != "y":
            print("Aborted.")
            return

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote unified .env to {OUTPUT}")
    print(f"  Total lines: {len(content.splitlines())}")

    envs = {k: read_env(v) for k, v in TOOLKIT_ENVS.items()}
    total = sum(len(v) for v in envs.values())
    found = sum(1 for v in envs.values() if v)
    print(f"  Sources read: {found}/{len(TOOLKIT_ENVS)}")
    print(f"  Legacy vars processed: {total}")


if __name__ == "__main__":
    main()
