"""Cookie sync endpoint for the ig_ingest bridge.

Extracted from ``__init__.py`` per PERF-003 step 9
(``docs/plans/perf-file-splits.md`` §4B).

The extension POSTs its live logged-in cookies here so the headless
Instagram collector can pick them up as a Netscape ``cookies.txt`` — this
prevents the headless path from running with a stale session and racking
up 401s that look bot-like.
"""
import logging
import os
import re
from pathlib import Path

from aiohttp import web

from .cors import _cors


logger = logging.getLogger("social_ingest")


async def cookies_handler(request):
    """Self-healing sessions: extension pushes live logged-in cookies for headless replay."""
    from . import CREDENTIALS_ROOT, _norm_platform, _safe_json

    body = await _safe_json(request)
    platform = _norm_platform(body.get("platform"))
    if platform != "instagram":
        return _cors(web.json_response({"ok": False, "reason": "unsupported"}))
    cookies = body.get("cookies") or []
    have = {c.get("name") for c in cookies if isinstance(c, dict)}
    if "sessionid" not in have:  # not logged in — don't clobber a good file with junk
        return _cors(web.json_response({"ok": False, "reason": "no sessionid"}))
    account = re.sub(r"[^A-Za-z0-9_.-]", "_", str(body.get("account") or "extension_live"))[:60]
    lines = ["# Netscape HTTP Cookie File", "# generated by the UnifiedCollector extension", ""]
    for c in cookies:
        if not isinstance(c, dict) or not c.get("name"):
            continue
        domain = c.get("domain") or ".instagram.com"
        inc_sub = "TRUE" if domain.startswith(".") else "FALSE"
        path = c.get("path") or "/"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expiry = int(c.get("expirationDate") or 0)
        lines.append(f"{domain}\t{inc_sub}\t{path}\t{secure}\t{expiry}\t{c['name']}\t{c.get('value','')}")
    try:
        d = Path(CREDENTIALS_ROOT) / "instagram"
        d.mkdir(parents=True, exist_ok=True)
        tmp = d / (account + ".txt.tmp")
        tmp.write_text("\n".join(lines) + "\n")
        os.replace(tmp, d / (account + ".txt"))
        logger.info("cookies: wrote live session for instagram/%s (%d cookies)", account, len(cookies))
    except Exception as e:
        logger.warning("cookies write failed: %s", e)
        return _cors(web.json_response({"ok": False, "error": str(e)}, status=500))
    return _cors(web.json_response({"ok": True, "account": account}))
