"""Credential parser for the instagram_dm collector (Option A of #39).

Local-only — reads files from `credentials/instagram_dm/`, refuses to load
if `creds_dir` accidentally resolves to `credentials/instagram/` (the main
IG collector's cookie jar), refuses on empty / malformed files.

Schema (one file per account, ``<username>.txt``):

    username: <mobile-app-account-handle>
    password: <plaintext-password-for-encrypted-login>

Optional (all persist across restarts if provided):
    mid: <cookie value>
    ig_did: <cookie value>
    sessionid: <cookie value from a prior successful login>

`device_id` / `family_device_id` / `phone_id` are NOT in this file —
they're generated by `device.load_or_create` and stored alongside as
`<username>.device.json` so churn between restarts is impossible.
`session_id` / auth tokens post-login are stored in `<username>.session.json`.

Passwords stay plaintext here because the mobile-API login endpoint
encrypts them per-request with a rotating RSA pubkey (fetched at login
time). Persisting the encrypted form doesn't help — the ciphertext is
single-use.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class Credentials:
    username: str
    password: str
    mid: str | None = None
    ig_did: str | None = None
    sessionid: str | None = None
    source_path: Path | None = None


_REQUIRED = ("username", "password")


def _parse_file(path: Path) -> dict:
    """Parse a `key: value` per-line file. Blank lines + `#` comments allowed.
    Unknown keys are preserved for forward compat but the returned dict is
    filtered down to Credentials fields at the call site."""
    out: dict[str, str] = {}
    for lineno, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            logger.warning("%s:%d ignoring line without ':' -> %r", path, lineno, raw)
            continue
        k, _, v = line.partition(":")
        out[k.strip().lower()] = v.strip()
    return out


def load_all(creds_dir: Path) -> list[Credentials]:
    """Return every valid Credentials in the directory. Ignores device.json
    and session.json companion files.

    Enforces the isolation invariant one more time here (belt-and-suspenders
    with the guard in `__init__.py::collect`): refuses if `creds_dir`
    resolves to `credentials/instagram/`.
    """
    creds_dir = Path(creds_dir)
    real = creds_dir.resolve()
    main_ig = Path("credentials/instagram").resolve()
    if real == main_ig:
        raise RuntimeError(
            "instagram_dm credentials path points at credentials/instagram — "
            "cross-contamination with the main IG collector is not allowed. "
            "Point INSTAGRAM_DM_CREDENTIALS_DIR at a separate directory."
        )
    if not real.exists():
        raise RuntimeError(f"instagram_dm credentials dir {real} does not exist")

    creds_list: list[Credentials] = []
    for f in sorted(real.glob("*.txt")):
        if f.name.endswith(".device.json") or f.name.endswith(".session.json"):
            continue
        try:
            fields = _parse_file(f)
        except OSError as e:
            logger.warning("could not read %s: %s", f, e)
            continue
        missing = [k for k in _REQUIRED if not fields.get(k)]
        if missing:
            logger.warning("%s missing required fields %s — skipping", f, missing)
            continue
        creds_list.append(Credentials(
            username=fields["username"],
            password=fields["password"],
            mid=fields.get("mid") or None,
            ig_did=fields.get("ig_did") or None,
            sessionid=fields.get("sessionid") or None,
            source_path=f,
        ))
    if not creds_list:
        logger.info(
            "instagram_dm found no valid credentials in %s (looking for "
            "*.txt with 'username:' and 'password:' lines — see the README "
            "in that directory)", real,
        )
    return creds_list
